### PR TITLE
reopen  channels

### PR DESCRIPTION
**Pull request by catShaark**
## Summary of changes

What changed:

reopen channel 1 49 20

How was it changed:

I change the code in begin blocker so that it set those channel to be OPEN

Link to GitHub issue tracker:
## Report of required housekeeping

- [ ] Github issue OR spec proposal link
- [ ] Wrote tests
- [ ] Updated API documentation (client/lcd/swagger-ui/swagger.yaml)
- [ ] Added a relevant changelog entry: clog add [section] [stanza] [message]

----

## (FOR ADMIN) Before merging

- [ ] Added appropriate labels to PR
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" (coding standards)
- [ ] Confirm added tests are consistent with the intended behavior of changes
- [ ] Ensure all tests pass

### CODE REVIEW

**Comment by faddat** [comment]
Hey Khanh, one thing before merging -- should we do this upgrade handler style instead of beginblocker style?


or have I lost the plot?

**Comment by catShaark** [comment]
I've checked the code at osmosis for reference. It seems like the change is a non-software upgrade ( meaning we only change the data with the fork logic, no sdk logic is changed ), this is classified as a [fork](https://github.com/osmosis-labs/osmosis/blob/1e80a2a220911cbd776f68e8fa5655870a5f5d98/app/upgrades/types.go#L40) according to the osmosis repo. A fork logic is handled by beginblocker.

**Comment by faddat** [comment]
love it.

**Comment by vuong177** [comment]
@faddat @catShaark I see fork block is 10 000 000. Should we change it when cut a release and gov upgrade ?

**Pull request merged**
